# Default values for nbxplorer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

config:
  rpcauth: ""

nbxplorer:
  network: regtest
  chain: btc
  rpcurl: "http://bitcoind.bitcoin.svc.cluster.local:8332/"
  nodeEndpoint: "bitcoind.bitcoin.svc.cluster.local:8333"

image:
  repository: nicolasdorier/nbxplorer
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

persistence:
  enabled: true
  ## Set storageClassName if you have no default defined. For geth you need an fast (ssd) disk to keep up
  #storageClassName: ""
  size: 1Gi

rabbitmq:
  auth:
    username: "rabbituser"
    password: ""
    erlangCookie: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 32838

ingress:
  enabled: false
  annotations:
    {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}


settingsConfig: |
    bind=0.0.0.0:32838
    network=regtest
    chains=btc
    btcrpcurl=http://btcpayserver-bitcoin-core-0:43782
    btcnodeendpoint=btcpayserver-bitcoin-core-0:39388
    btcrpcauth=ceiwHEbqWI83:XB62kURh0JUTOhIpC-WV7X6m4jGuVvwsyQV4m_EP9C4=
    rmquser="rabbituser"
    rmqpass=""
    rmqhost=nbxplorer-rabbitmq
    rmqvirtual=/
    rmqtranex=NewTransaction
    rmqblockex=NetBlock
