apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "btcpayserver.fullname" . }}
  annotations:
    cert-manager.io/issuer: {{ include "btcpayserver.fullname" . }}
    cert-manager.io/acme-challenge-type: http01

spec:
  tls:
    - hosts:
        - {{.Values.ingress.host}}
      secretName: {{.Values.ingress.service.cert}}

  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.Values.ingress.service.name}}
                port:
                  number: {{.Values.ingress.service.port}}
  ingressClassName: nginx
          # - path: /.well-known/acme-challenge/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{.Values.ingress.service.name}}
          #       port:
          #         number: {{.Values.ingress.service.port}}
