apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "btcpayserver.fullname" . }}-ingress
  annotations:
    cert-manager.io/acme-challenge-type: http01
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      # Dedicated location for ACME challenges
      location /.well-known/acme-challenge/* {
          default_type text/plain;
          return 200 http://$host$request_uri;
      }
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.service.cert }}
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.service.name }}
                port:
                  number: {{ .Values.ingress.service.port }}


          # - path: /.well-known/acme-challenge/
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: {{.Values.ingress.service.name}}
          #       port:
          #         number: {{.Values.ingress.service.port}}
