{{- if .Values.ingress }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "btcpayserver.fullname" . }}-issuer
spec:
  acme:
    server: {{.Values.ingress.issuer.server}} 
    email: {{ .Values.ingress.issuer.email }}
    privateKeySecretRef:
      name: btcpayserver-issuer-key
    solvers:
        - http01:
            ingress:
                class: nginx

{{- end }} 