apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "btcpayserver.fullname" .}}-plugins"
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "btcpayserver.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi