[package]
name = "starter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

bitcoin={ version = "0.31.2", features=["rand","std","rand-std"]}

bitcoincore-rpc = "0.18.0"
postgres = "0.19.7"
