apiVersion: batch/v1
kind: Job
metadata:
  name: starter
spec:
  template:
    spec:
      containers:
      - name: my-job-container
        image: localhost:5000/starter:latest
        args: 
        - --network=testnet
      restartPolicy: Never
