bitcoin-core:
  service:
    ports:
      rpc: 43782
      p2p: 39388
    extraPorts:
      - name: zmqpubrawblock 
        port: 28332
        targetPort:  28332
      - name: zmqpubrawtx
        port: 28333
        targetPort: 28333
 
  persistence:
    accessMode: ReadWriteOnce
    size: 64Gi
  config: |
    server=1
    testnet=1
    rpcserialversion=0
    rpcuser=ceiwHEbqWI83
    rpcpassword=XB62kURh0JUTOhIpC-WV7X6m4jGuVvwsyQV4m_EP9C4=
    whitelist=127.0.0.1
    whitebind=0.0.0.0:39388

    [test]
    blockfilterindex=1
    peerblockfilters=1
    debug=rpc
    rpcallowip=0.0.0.0/0
    rpcbind=0.0.0.0
    prune=550
    dbcache=75
    maxorphantx=10
    maxmempool=150
    nodebuglogfile=1
    zmqpubrawblock=tcp://0.0.0.0:28332
    zmqpubrawtx=tcp://0.0.0.0:28333
    deprecatedrpc=signrawtransaction
    fallbackfee=0.0002
    rpcport=43782

lnd:
  loop:
    enable: false
  pool:
    enable: false
  configurationFile:
    lnd.conf: |-
      bitcoin.node=bitcoind
      accept-amp=1
      bitcoin.active=1
      bitcoin.testnet=1
      bitcoind.rpchost=btcpayserver-bitcoin-core-0:43782
      bitcoind.rpcuser=ceiwHEbqWI83
      bitcoind.rpcpass=XB62kURh0JUTOhIpC-WV7X6m4jGuVvwsyQV4m_EP9C4=
      bitcoind.zmqpubrawblock=tcp://btcpayserver-bitcoin-core-0:28332
      bitcoind.zmqpubrawtx=tcp://btcpayserver-bitcoin-core-0:28333
      bitcoin.defaultchanconfs=1
      debuglevel=debug
      trickledelay=1000
      rpclisten=0.0.0.0:10009
      restlisten=0.0.0.0:8080
  internalServices:
    rpcPort: 10009
    restPort: 8080
  # Ports that are visible outside your cluster
  externalServices:
    p2pPort: 9735
  persistence:
    size: 1Gi

nbxplorer:
  rabbitmq:
    persistence:
      size: 16Gi
  service:
    type: ClusterIP
    port: 32838
  persistence:
    size: 8Gi
  settingsConfig: |
    bind=0.0.0.0:32838 
    btcnodeendpoint=btcpayserver-bitcoin-core-0:39388 
    btcrpcauth=ceiwHEbqWI83:XB62kURh0JUTOhIpC-WV7X6m4jGuVvwsyQV4m_EP9C4= 
    btcrpcurl=http://btcpayserver-bitcoin-core-0:43782 
    chains=btc 
    exposerpc=1
    network=testnet 
    noauth=true
    postgres=User ID=btcpayadmin;Password=p@ssw0rd!;Include Error Detail=true;Host=btcpayserver-postgresql;Port=5432;Database=nbxplorer
    rmqblockex=NetBlock 
    rmqhost=nbxplorer-rabbitmq 
    rmqpass="" 
    rmqtranex=NewTransaction 
    rmquser="rabbituser" 
    rmqvirtual=/
    verbose=1
    btcrescan=1


postgresql:
  auth:
    username: btcpayadmin
    password: p@ssw0rd!
  primary:
    initdb: 
      user: btcpayadmin
      password: p@ssw0rd!
      database: testDB
      scripts:
        my_script.sql: |
          CREATE DATABASE nbxplorer; 
          CREATE DATABASE btcpayserver;
        my_init_script.sh: |
          #!/bin/sh
          echo "executing script"
    persistence:
      size: 1Gi
  readReplicas:
    persistence:
      size: 1Gi
  image:
    debug: true

rtl:
  service:
    port: 80
    targetPort: 3000
  configMap:
    jsonContent: |
      {
        "port": "3000",
        "defaultNodeIndex": 1,
        "dbDirectoryPath": "/root/database/node-1",
        "SSO": {
          "rtlSSO": 0,
          "rtlCookiePath": "",
          "logoutRedirectLink": ""
        },
        "nodes": [
          {
            "index": 1,
            "lnNode": "Node 1",
            "lnImplementation": "LND",
            "Authentication": {
              "macaroonPath": "/RTL/data/chain/bitcoin/testnet",
              "configPath": "/RTL/data/lnd.conf"
            },
            "Settings": {
              "userPersona": "MERCHANT",
              "themeMode": "DAY",
              "themeColor": "PURPLE",
              "channelBackupPath": "/root/backup/node-1",
              "logLevel": "ERROR",
              "lnServerUrl": "https://btcpayserver-lnd-internal:8080",
              "fiatConversion": false,
              "unannouncedChannels": false
            }
          }
        ],
        "multiPassHashed": "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"
      }


env:  
  BTCPAY_NETWORK: 'testnet'
  BTCPAY_POSTGRES: "User ID=btcpayadmin;Password=p@ssw0rd!;Include Error Detail=true;Host=btcpayserver-postgresql;Port=5432;Database=btcpayserver"
  BTCPAY_EXPLORERPOSTGRES: "User ID=btcpayadmin;Password=p@ssw0rd!;Include Error Detail=true;Host=btcpayserver-postgresql;Port=5432;Database=nbxplorer"
  BTCPAY_BTCEXPLORERURL: "http://btcpayserver-nbxplorer:32838"
  BTCPAY_BTCEXTERNALLNDREST: "type=lnd-rest;server=http://btcpayserver-lnd-internal:8080/;allowinsecure=true"
  BTCPAY_VERBOSE: "true"
  BTCPAY_DEBUGLOG: "debug.log"
  ASPNETCORE_URLS: "http://*:23002"
  BTCPAY_ALLOW-ADMIN-REGISTRATION: "true"
  BTCPAYGEN_LIGHTNING: 'lnd'
  BTCPAYGEN_ADDITIONAL_FRAGMENTS: "$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-add-btctransmuter"
  BTCPAY_PORT: "23002"
  BTCPAY_BIND: 0.0.0.0:23002
  BTCPAYGEN_ADDITIONAL_FRAGMENTS: $BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-add-btctransmuter

pvc:
  name: btcpayserver-plugin
  storage: 2Gi

ingress: 
  issuer:
    email: 1asdfah@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory

  btcpay:
    host: testnet.spos.live
    service:
      port: 80
      name: btcpayserver

  rtl:
    host: rtl.spos.live
    service:
      port: 80
      name: btcpayserver-rtl

service:
  type: LoadBalancer
  port: 80
  targetPort: 23002
  

