apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name}}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "btctransmuter.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.pvc.size}}